---
title: "Reading data from the web"
author: "Soomin You"
date: "2024-10-10"
output: html_document
---

```{r setup, include=FALSE}
library(rvest)
library(httr)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

Get the pieces I actually need. 

```{r}
marj_use_df = 
  drug_use_html |>
  html_table() |> 
  first() |>
  slice(-1)
```

Learning Assessment 

```{r}
cost_living_nyc = read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york")

cost_living_nyc |>
  html_table(header = TRUE)
```


## CSS Selectors!! 

```{r}
swm_url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(swm_url)
```


```{r}
swm_title_vec = 
  swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()

swm_runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_score_vec = 
  swm_html |>
  html_elements(".ipc-rating-star--rating") |>
  html_text()

swm_df = 
  tibble(
    title = swm_title_vec, 
    runtime = swm_runtime_vec, 
    score = swm_score_vec
  )
```


Let's import some books. 

```{r}
books_html = read_html("http://books.toscrape.com")

books_html |>
  html_elements(".price_color") |>
  html_text()
```


## Use API 

Get water data. 

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") |>
  content()
```

Get BRFSS data 

```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv", 
      query = list("$limit" = 5000)) |>
  content()
```



Pokemon API 

```{r}
pokemon = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |>
  content()
```


```{r}
pokemon$height
pokemon$abilities
```


